name: Cache CocoaPods
description: Cache CocoaPods dependencies and lock file

runs:
  using: "composite"
  steps:
    - name: Cache CocoaPods
      uses: actions/cache@v4
      with:
        path: |
          ios/Pods
          ios/Podfile.lock
          ~/.cocoapods
        key: cocoapods-${{ runner.os }}-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: |
          cocoapods-${{ runner.os }}-
