name: Flutter iOS CI Pipeline

run-name: ${{ github.actor }} triggered Flutter iOS CI pipeline

on:
  pull_request:
    branches:
      - master
      - develop

env:
  FLUTTER_VERSION: 3.32.8

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # lint 단계에서 pubspec.yaml에 정의한 env 파일 존재 여부를 체크하므로 필요
      - name: Setup .env file
        uses: ./.github/actions/setup-env
        with:
          tmdb-api-key: ${{ secrets.TMDB_API_KEY }}

      - name: Run Lint (flutter analyze)
        run: flutter analyze > lint-report.txt
      
      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flutter-lint-report
          path: lint-report.txt
        continue-on-error: true

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup .env file
        uses: ./.github/actions/setup-env
        with:
          tmdb-api-key: ${{ secrets.TMDB_API_KEY }}

      - name: Run Unit Tests
        run: flutter test > test-report.txt

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: flutter-unit-test-report
          path: test-report.txt
        continue-on-error: true

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup .env file
        uses: ./.github/actions/setup-env
        with:
          tmdb-api-key: ${{ secrets.TMDB_API_KEY }}

      - name: Cache CocoaPods
        uses: ./.github/actions/cache-cocoapods

      - name: Build iOS
        run: flutter build ios --no-codesign

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
        continue-on-error: true

  integration-test:
    name: Integration Test
    runs-on: macos-latest
    needs: build-ios
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
  
      - name: Setup .env file
        uses: ./.github/actions/setup-env
        with:
          tmdb-api-key: ${{ secrets.TMDB_API_KEY }}
  
      - name: Show available simulators
        run: xcrun simctl list devices
  
      - name: Launch iOS Simulator
        run: |
          xcrun simctl boot "iPhone 16 Pro Max"
          open -a Simulator
          sleep 10
  
      - name: Run Integration Tests
        run: flutter test integration_test > integration-test-report.txt
  
      - name: Upload Integration Test Report
        uses: actions/upload-artifact@v4
        with:
          name: flutter-integration-test-report
          path: integration-test-report.txt
        continue-on-error: true
